"""Render a plan JSON dict into a professional Markdown test plan.

The model returns JSON; THIS module owns the Markdown template. The model
never sees this template and cannot drift from it.
"""


def _fmt_scope(plan: dict) -> str:
    lines = []
    for item in plan.get("scope", []):
        lines.append(f"- **{item.get('entry', '')}**")
        jb = item.get("justified_by", "")
        if jb:
            lines.append(f"  - *justified by:* {jb}")
    return "\n".join(lines) if lines else "- TBD"


def _fmt_test_cases(plan: dict) -> str:
    rows = []
    for tc in plan.get("test_cases", []):
        steps = "\n".join(f"  {i + 1}. {s}" for i, s in enumerate(tc.get("steps", [])))
        rows.append(
            f"### {tc.get('id', 'TC?')} - {tc.get('title', '')}\n\n"
            f"**Precondition:** {tc.get('precondition', '')}\n\n"
            f"**Steps:**\n{steps}\n\n"
            f"**Expected:** {tc.get('expected', '')}\n"
        )
    return "\n".join(rows) if rows else "TBD"


def _fmt_list(items) -> str:
    return "\n".join(f"- {i}" for i in items) if items else "- TBD"


def render_plan_markdown(ticket: dict, plan: dict) -> str:
    """Return the final Markdown test plan document."""
    title = f"Test Plan - {ticket.get('summary') or ticket.get('key')}"
    return f"""# {title}

**Jira:** [{ticket.get('key')}]({ticket.get('url', '#')}) · **Type:** {ticket.get('issue_type')} · **Status:** {ticket.get('status')} · **Priority:** {ticket.get('priority')}

## 1. Objective

{plan.get('objective', 'TBD')}

## 2. Scope

{_fmt_scope(plan)}

## 3. Test Environments

{_fmt_list(plan.get('environments', []))}

## 4. Entry Criteria

{_fmt_list(plan.get('entry_criteria', []))}

## 5. Exit Criteria

{_fmt_list(plan.get('exit_criteria', []))}

## 6. Test Cases

{_fmt_test_cases(plan)}

## 7. Risks & Mitigations

{_fmt_risks(plan.get('risks', []))}

## 8. Deliverables

{_fmt_list(plan.get('deliverables', []))}

## 9. Assumptions

{_fmt_list(plan.get('assumptions', []))}

---
*Generated by the Test Plan Agent. Source ticket facts only; see assumptions for anything not directly on the ticket.*
"""


def _fmt_risks(risks) -> str:
    if not risks:
        return "- TBD"
    return "\n".join(f"- **{r.get('risk', '')}** - {r.get('mitigation', '')}" for r in risks)
